--------------------------------------------------------
--  文件已创建 - 星期五-四月-06-2018   
--------------------------------------------------------
REM INSERTING into CZSP.BASE_DIC
SET DEFINE OFF;
Insert into CZSP.BASE_DIC (DIC_ID,TABLE_NAME) values ('20000','DIC_QX');
Insert into CZSP.BASE_DIC (DIC_ID,TABLE_NAME) values ('18100','DIC_WF_PHASE');
Insert into CZSP.BASE_DIC (DIC_ID,TABLE_NAME) values ('18110','DIC_WF_NODE');
Insert into CZSP.BASE_DIC (DIC_ID,TABLE_NAME) values ('19100','DIC_AHTU_DEPT');
Insert into CZSP.BASE_DIC (DIC_ID,TABLE_NAME) values ('19110','DIC_AHTU_ROLE');
Insert into CZSP.BASE_DIC (DIC_ID,TABLE_NAME) values ('30000','DIC_PERMISSION_TYPE');
Insert into CZSP.BASE_DIC (DIC_ID,TABLE_NAME) values ('20010','DIC_QX_CZ');
REM INSERTING into CZSP.DIC_AHTU_DEPT
SET DEFINE OFF;
Insert into CZSP.DIC_AHTU_DEPT (ID,NAME,CODE) values ('CZC','村镇处',null);
Insert into CZSP.DIC_AHTU_DEPT (ID,NAME,CODE) values ('XKC','许可处',null);
Insert into CZSP.DIC_AHTU_DEPT (ID,NAME,CODE) values ('BGS','办公室',null);
Insert into CZSP.DIC_AHTU_DEPT (ID,NAME,CODE) values ('CGB','成果办',null);
Insert into CZSP.DIC_AHTU_DEPT (ID,NAME,CODE) values ('ZB','在编',null);
Insert into CZSP.DIC_AHTU_DEPT (ID,NAME,CODE) values ('JLD','局领导',null);
REM INSERTING into CZSP.DIC_AHTU_ROLE
SET DEFINE OFF;
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('XKC_JBR','许可处经办人',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('CZC_JBR','村镇处经办人',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('CZC_FC','村镇处副处',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('CZC_CZ','村镇处处长',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('JLD_JZ','局长',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('BGS_JBR','办公室经办人',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('QX_JBR','区县经办人',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('CGB_JBR','成果办经办人',null);
Insert into CZSP.DIC_AHTU_ROLE (ID,NAME,CODE) values ('ADMIN','管理员',null);
REM INSERTING into CZSP.DIC_PERMISSION_TYPE
SET DEFINE OFF;
Insert into CZSP.DIC_PERMISSION_TYPE (ID,NAME,CODE) values ('01','菜单',null);
Insert into CZSP.DIC_PERMISSION_TYPE (ID,NAME,CODE) values ('02','按钮',null);
Insert into CZSP.DIC_PERMISSION_TYPE (ID,NAME,CODE) values ('03','页面',null);
REM INSERTING into CZSP.DIC_QX
SET DEFINE OFF;
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('00','市局','SJ');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('01','黄浦区','HP');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('02','徐汇区','XH');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('03','长宁区','CN');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('04','静安区','JN');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('05','普陀区','PT');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('06','虹口区','HK');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('07','杨浦区','YP');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('08','浦东新区','PD');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('09','闵行区','MH');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('10','宝山区','BS');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('11','嘉定区','JD');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('12','金山区','JS');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('13','松江区','SJ');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('14','青浦区','QP');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('15','奉贤区','FX');
Insert into CZSP.DIC_QX (ID,NAME,CODE) values ('16','崇明区','CM');
REM INSERTING into CZSP.DIC_QX_CZ
SET DEFINE OFF;
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('02001','华泾镇','HJZ','02');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('03001','新泾镇','XJZ','03');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('04001','彭浦镇','PPZ','04');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('05001','长征镇','CZZ','05');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('05002','桃浦镇','TPZ','05');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('07001','五角场镇','WJCZ','07');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08001','川沙新镇','CSXZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08002','高桥镇','GQZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08003','北蔡镇','BCZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08004','合庆镇','HQZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08005','唐镇','TZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08006','曹路镇','CLZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08007','金桥镇','JQZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08008','高行镇','GHZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08009','高东镇','GDZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08010','张江镇','ZJZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08011','三林镇','SLZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08012','惠南镇','HNZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08013','周浦镇','ZPZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08014','新场镇','XCZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08015','大团镇','DTZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08016','康桥镇','KQZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08017','航头镇','HTZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08018','祝桥镇','ZQZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08019','泥城镇','NCZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08020','宣桥镇','XQZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08021','书院镇','SYZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08022','万祥镇','WXZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08023','老港镇','LGZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('08024','南汇新城镇','NHXCZ','08');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09001','莘庄镇','XZZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09002','七宝镇','QBZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09003','浦江镇','PJZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09004','梅陇镇','MLZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09005','虹桥镇','HQZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09006','马桥镇','MQZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09007','吴泾镇','WJZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09008','华漕镇','HCZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('09009','颛桥镇','ZQZ','09');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10001','罗店镇','LDZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10002','大场镇','DCZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10003','杨行镇','YHZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10004','月浦镇','YPZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10005','罗泾镇','LJZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10006','顾村镇','GCZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10007','高泾镇','GJZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10008','庙行镇','MHZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('10009','淞南镇','SNZ','10');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('11001','南翔镇','NXZ','11');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('11002','安亭镇','ATZ','11');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('11003','马陆镇','MLZ','11');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('11004','徐行镇','XHZ','11');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('11005','华亭镇','HTZ','11');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('11006','外冈镇','WGZ','11');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('11007','江桥镇','JQZ','11');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12001','朱泾镇','ZJZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12002','枫泾镇','FJZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12003','张堰镇','ZYZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12004','亭林镇','TLZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12005','吕巷镇','LXZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12006','廊下镇','LXZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12007','金山卫镇','JSWZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12008','漕泾镇','CJZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('12009','山阳镇','SYZ','12');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13001','泗泾镇','SJZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13002','佘山镇','SSZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13003','车墩镇','CDZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13004','新桥镇','XQZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13005','洞泾镇','DJZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13006','九亭镇','JTZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13007','泖港镇','MGZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13008','石湖荡镇','SHDZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13009','新浜镇','XBZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13010','叶榭镇','YXZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('13011','小昆山镇','XKSZ','13');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14001','朱家角镇','ZJJZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14002','赵巷镇','ZXZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14003','徐泾镇','XJZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14004','华新镇','HXZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14005','重固镇','CGZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14006','白鹤镇','BHZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14007','练塘镇','LTZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('14008','金泽镇','JZZ','14');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15001','南桥镇','NQZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15002','丰城镇','FCZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15003','四团镇','STZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15004','柘林镇','ZLZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15005','庄行镇','ZHZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15006','金汇镇','JHZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15007','青村镇','QCZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('15008','海湾镇','HWZ','15');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16001','城桥镇','CQZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16002','堡镇','BZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16003','新河镇','XHZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16004','竖新镇','SXZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16005','向化镇','XHZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16006','三星镇','SXZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16007','港沿镇','GYZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16008','中兴镇','ZXZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16009','陈家镇','CJZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16010','绿华镇','LHZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16011','港西镇','GXZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16012','建设镇','JSZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16013','新海镇','XHZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16014','东平镇','DPZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16015','长兴镇','CXZ','16');
Insert into CZSP.DIC_QX_CZ (ID,NAME,CODE,QX_ID) values ('16016','庙镇','MZ','16');
REM INSERTING into CZSP.DIC_WF_NODE
SET DEFINE OFF;
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110100','开始',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110101','办理',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110102','结束',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110200','开始',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110201','上报申请',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110202','受理',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110203','签分',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110204','办理',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110205','副处审核',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110206','处长审核',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110207','局长审定',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110208','文印发件',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110209','结束',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110300','开始',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110301','入库',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110302','归档',null);
Insert into CZSP.DIC_WF_NODE (ID,NAME,CODE) values ('110303','结束',null);
REM INSERTING into CZSP.DIC_WF_PHASE
SET DEFINE OFF;
Insert into CZSP.DIC_WF_PHASE (ID,NAME,CODE) values ('1101','基础准备','JCZB');
Insert into CZSP.DIC_WF_PHASE (ID,NAME,CODE) values ('1102','方案审批','FASP');
Insert into CZSP.DIC_WF_PHASE (ID,NAME,CODE) values ('1103','成果入库','CGRK');
